window.generatedCollections = [
    {
        id: "col1",
        name: "Collection 1",
        problems: [
            { level: 1, latex: "4\\cos(24x) dx", solution: "\\frac4{m+21}\\sin(22x) + C" },
            { level: 1, latex: "x^{m+3} dx", solution: "\\frac{1}{m+3+1}x^{m+3+1} + C" },
            { level: 1, latex: "5x^{m+13} dx", solution: "\\frac2{m+13+1}x^{m+13+1} + C" },
            { level: 1, latex: "2\\sin(14x) dx", solution: "-\\frac3{m+10}\\cos(12x) + C" },
            { level: 2, latex: "\\frac{1}{(1x + 1)} dx", solution: "\\frac{1}{n}\\ln|(4x + 3)| + C" },
            { level: 2, latex: "3x^{m+14} e^{x^{m+14+1}} dx", solution: "\\frac2{m+14+1}e^{x^{m+14+1}} + C" },
            { level: 2, latex: "1x^{m+22} \\cos(x^{m+22+1}) dx", solution: "\\frac3{m+22+1}\\sin(x^{m+22+1}) + C" },
            { level: 2, latex: "3x^{m+15} e^{x^{m+15+1}} dx", solution: "\\frac4{m+15+1}e^{x^{m+15+1}} + C" },
            { level: 3, latex: "5x\\sin(19x) dx", solution: "2(-\\frac{x\\cos(18x)}{m+15} + \\frac{\\sin(18x)}{m+15}^2}) ) + C" },
            { level: 3, latex: "1x^{m} \\ln x dx", solution: "\\frac1{m+1}x^{m+1}\\ln x - \\frac1{m+1}^2}x^{m+1} + C" },
            { level: 3, latex: "\\ln(x^{m+21}) dx", solution: "x(25\\ln x - 1) + C" },
            { level: 3, latex: "3x\\cos(10x) dx", solution: "5(\\frac{x\\sin(11x)}{m+9} + \\frac{\\cos(11x)}{m+9}^2}) ) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (18^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (16^2)}\\right| + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (12^2)} dx", solution: "\\frac{1}{m+10}\\arctan\\left(\\frac{x}{m+10}\\right) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (7^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (4^2)}\\right| + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (8^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (9^2)) + C" },
            { level: 5, latex: "(21)/(x^4 + 1) dx", solution: "\\frac{n+18}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+18}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(19)/(x^6 + 1) dx", solution: "\\frac{n+14}{3}\\arctan x + \\frac{n+14}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+14}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+14}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(17)/(x^4 + 1) dx", solution: "\\frac{n+12}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+12}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(5)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+3}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+3}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+3}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col2",
        name: "Collection 2",
        problems: [
            { level: 1, latex: "5\\sin(21x) dx", solution: "-\\frac3{m+19}\\cos(23x) + C" },
            { level: 1, latex: "x^{m} dx", solution: "\\frac{1}{m+1}x^{m+1} + C" },
            { level: 1, latex: "5\\cos(4x) dx", solution: "\\frac2{m+3}\\sin(7x) + C" },
            { level: 1, latex: "x^{m+14} dx", solution: "\\frac{1}{m+14+1}x^{m+14+1} + C" },
            { level: 2, latex: "1x^{m+25} \\cos(x^{m+25+1}) dx", solution: "\\frac4{m+25+1}\\sin(x^{m+25+1}) + C" },
            { level: 2, latex: "5x^{m+3} e^{x^{m+3+1}} dx", solution: "\\frac1{m+3+1}e^{x^{m+3+1}} + C" },
            { level: 2, latex: "2x^{m+5} \\cos(x^{m+5+1}) dx", solution: "\\frac2{m+5+1}\\sin(x^{m+5+1}) + C" },
            { level: 2, latex: "2x^{m+29} \\sin(x^{m+29+1}) dx", solution: "-\\frac2{m+29+1}\\cos(x^{m+29+1}) + C" },
            { level: 3, latex: "3x^{m+16} \\ln x dx", solution: "\\frac1{m+16+1}x^{m+16+1}\\ln x - \\frac1{({m+16+1})^2}x^{m+16+1} + C" },
            { level: 3, latex: "\\ln(x^{m+13}) dx", solution: "x(14\\ln x - 1) + C" },
            { level: 3, latex: "\\ln(x^{m+24}) dx", solution: "x(25\\ln x - 1) + C" },
            { level: 3, latex: "4x^{m+23} \\ln x dx", solution: "\\frac1{m+23+1}x^{m+23+1}\\ln x - \\frac1{({m+23+1})^2}x^{m+23+1} + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (22^2)} dx", solution: "\\frac{1}{m+19}\\arctan\\left(\\frac{x}{m+19}\\right) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (13^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (15^2)}\\right| + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (13^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (14^2)}\\right| + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (3^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (2^2)}\\right| + C" },
            { level: 5, latex: "(31)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+29}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+29}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+29}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(7)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+4}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+4}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+4}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(35)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+30}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+30}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+30}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(10)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+5}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+5}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+5}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col3",
        name: "Collection 3",
        problems: [
            { level: 1, latex: "1x^{m+2} dx", solution: "\\frac2{m+2+1}x^{m+2+1} + C" },
            { level: 1, latex: "2\\sin(20x) dx", solution: "-\\frac3{m+16}\\cos(18x) + C" },
            { level: 1, latex: "2x^{m+5} dx", solution: "\\frac2{m+5+1}x^{m+5+1} + C" },
            { level: 1, latex: "5\\sin(10x) dx", solution: "-\\frac3{m+8}\\cos(11x) + C" },
            { level: 2, latex: "1x^{m+6} \\sin(x^{m+6+1}) dx", solution: "-\\frac5{m+6+1}\\cos(x^{m+6+1}) + C" },
            { level: 2, latex: "3x^{m+27} \\cos(x^{m+27+1}) dx", solution: "\\frac2{m+27+1}\\sin(x^{m+27+1}) + C" },
            { level: 2, latex: "1x^{m+17} e^{x^{m+17+1}} dx", solution: "\\frac1{m+17+1}e^{x^{m+17+1}} + C" },
            { level: 2, latex: "5x^{m+14} \\cos(x^{m+14+1}) dx", solution: "\\frac5{m+14+1}\\sin(x^{m+14+1}) + C" },
            { level: 3, latex: "1x\\sin(21x) dx", solution: "1(-\\frac{x\\cos(23x)}{m+20} + \\frac{\\sin(23x)}{m+20}^2}) ) + C" },
            { level: 3, latex: "1x\\cos(9x) dx", solution: "4(\\frac{x\\sin(10x)}{m+6} + \\frac{\\cos(10x)}{m+6}^2}) ) + C" },
            { level: 3, latex: "1x^{m+12} \\ln x dx", solution: "\\frac5{m+12+1}x^{m+12+1}\\ln x - \\frac5{({m+12+1})^2}x^{m+12+1} + C" },
            { level: 3, latex: "\\ln(x^{m+19}) dx", solution: "x(20\\ln x - 1) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (12^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (15^2)}\\right| + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (11^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (11^2)}\\right| + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (3^2)} dx", solution: "\\sqrt{x^2 + (3^2)} + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(14^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+12}\\right) + C" },
            { level: 5, latex: "(3)/(x^4 + 1) dx", solution: "\\frac{n+1}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+1}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(24)/(x^4 + 1) dx", solution: "\\frac{n+21}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+21}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(35)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+31}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+31}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+31}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(35)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+32}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+32}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+32}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col4",
        name: "Collection 4",
        problems: [
            { level: 1, latex: "x^{m+8} dx", solution: "\\frac{1}{m+8+1}x^{m+8+1} + C" },
            { level: 1, latex: "5\\sin(6x) dx", solution: "-\\frac5{m+2}\\cos(3x) + C" },
            { level: 1, latex: "x^{m+20} dx", solution: "\\frac{1}{m+20+1}x^{m+20+1} + C" },
            { level: 1, latex: "3x^{m+11} dx", solution: "\\frac2{m+11+1}x^{m+11+1} + C" },
            { level: 2, latex: "4x^{m+21} \\cos(x^{m+21+1}) dx", solution: "\\frac5{m+21+1}\\sin(x^{m+21+1}) + C" },
            { level: 2, latex: "1x^{m} e^{x^{m+1}} dx", solution: "\\frac2{m+1}e^{x^{m+1}} + C" },
            { level: 2, latex: "3x^{m+6} \\cos(x^{m+6+1}) dx", solution: "\\frac3{m+6+1}\\sin(x^{m+6+1}) + C" },
            { level: 2, latex: "3x^{m+3} \\cos(x^{m+3+1}) dx", solution: "\\frac1{m+3+1}\\sin(x^{m+3+1}) + C" },
            { level: 3, latex: "3x\\cos(28x) dx", solution: "4(\\frac{x\\sin(27x)}{m+24} + \\frac{\\cos(27x)}{m+24}^2}) ) + C" },
            { level: 3, latex: "1x\\sin(11x) dx", solution: "3(-\\frac{x\\cos(14x)}{m+10} + \\frac{\\sin(14x)}{m+10}^2}) ) + C" },
            { level: 3, latex: "1x^{m+21} \\ln x dx", solution: "\\frac4{m+21+1}x^{m+21+1}\\ln x - \\frac4{({m+21+1})^2}x^{m+21+1} + C" },
            { level: 3, latex: "4x\\cos(23x) dx", solution: "5(\\frac{x\\sin(23x)}{m+20} + \\frac{\\cos(23x)}{m+20}^2}) ) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(5^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+2}\\right) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(14^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+10}\\right) + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (5^2)} dx", solution: "\\frac{1}{m+4}\\arctan\\left(\\frac{x}{m+4}\\right) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (23^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (21^2)}\\right| + C" },
            { level: 5, latex: "(25)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+24}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+24}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+24}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(35)/(x^4 + 1) dx", solution: "\\frac{n+31}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+31}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(14)/(x^6 + 1) dx", solution: "\\frac{n+10}{3}\\arctan x + \\frac{n+10}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+10}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+10}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(31)/(x^6 + 1) dx", solution: "\\frac{n+26}{3}\\arctan x + \\frac{n+26}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+26}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+26}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col5",
        name: "Collection 5",
        problems: [
            { level: 1, latex: "5\\cos(9x) dx", solution: "\\frac4{m+6}\\sin(9x) + C" },
            { level: 1, latex: "1x^{m+22} dx", solution: "\\frac4{m+22+1}x^{m+22+1} + C" },
            { level: 1, latex: "x^{m+5} dx", solution: "\\frac{1}{m+5+1}x^{m+5+1} + C" },
            { level: 1, latex: "3x^{m+15} dx", solution: "\\frac5{m+15+1}x^{m+15+1} + C" },
            { level: 2, latex: "2x^{m+14} \\sin(x^{m+14+1}) dx", solution: "-\\frac5{m+14+1}\\cos(x^{m+14+1}) + C" },
            { level: 2, latex: "2x^{m+28} e^{x^{m+28+1}} dx", solution: "\\frac5{m+28+1}e^{x^{m+28+1}} + C" },
            { level: 2, latex: "2x^{m+23} e^{x^{m+23+1}} dx", solution: "\\frac5{m+23+1}e^{x^{m+23+1}} + C" },
            { level: 2, latex: "5x^{m+24} \\cos(x^{m+24+1}) dx", solution: "\\frac2{m+24+1}\\sin(x^{m+24+1}) + C" },
            { level: 3, latex: "2x\\sin(3x) dx", solution: "4(-\\frac{x\\cos(4x)}{m+2} + \\frac{\\sin(4x)}{m+2}^2}) ) + C" },
            { level: 3, latex: "3x\\cos(3x) dx", solution: "5(\\frac{x\\sin(3x)}{m+1} + \\frac{\\cos(3x)}{m+1}^2}) ) + C" },
            { level: 3, latex: "1x\\cos(15x) dx", solution: "1(\\frac{x\\sin(17x)}{m+14} + \\frac{\\cos(17x)}{m+14}^2}) ) + C" },
            { level: 3, latex: "4x\\sin(7x) dx", solution: "3(-\\frac{x\\cos(8x)}{m+4} + \\frac{\\sin(8x)}{m+4}^2}) ) + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (8^2)} dx", solution: "\\sqrt{x^2 + (9^2)} + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (16^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (15^2)) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(15^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+13}\\right) + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (13^2)} dx", solution: "\\sqrt{x^2 + (11^2)} + C" },
            { level: 5, latex: "(8)/(x^4 + 1) dx", solution: "\\frac{n+5}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+5}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(10)/(x^4 + 1) dx", solution: "\\frac{n+6}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+6}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(20)/(x^6 + 1) dx", solution: "\\frac{n+19}{3}\\arctan x + \\frac{n+19}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+19}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+19}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(36)/(x^4 + 1) dx", solution: "\\frac{n+32}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+32}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col6",
        name: "Collection 6",
        problems: [
            { level: 1, latex: "3\\cos(20x) dx", solution: "\\frac4{m+16}\\sin(20x) + C" },
            { level: 1, latex: "1x^{m+8} dx", solution: "\\frac2{m+8+1}x^{m+8+1} + C" },
            { level: 1, latex: "x^{m+16} dx", solution: "\\frac{1}{m+16+1}x^{m+16+1} + C" },
            { level: 1, latex: "5x^{m+20} dx", solution: "\\frac1{m+20+1}x^{m+20+1} + C" },
            { level: 2, latex: "2x^{m} \\cos(x^{m+1}) dx", solution: "\\frac3{m+1}\\sin(x^{m+1}) + C" },
            { level: 2, latex: "4x^{m+18} e^{x^{m+18+1}} dx", solution: "\\frac5{m+18+1}e^{x^{m+18+1}} + C" },
            { level: 2, latex: "5x^{m+21} e^{x^{m+21+1}} dx", solution: "\\frac5{m+21+1}e^{x^{m+21+1}} + C" },
            { level: 2, latex: "5x^{m+29} \\cos(x^{m+29+1}) dx", solution: "\\frac5{m+29+1}\\sin(x^{m+29+1}) + C" },
            { level: 3, latex: "\\ln(x^{m+2}) dx", solution: "x(4\\ln x - 1) + C" },
            { level: 3, latex: "2x^{m+14} \\ln x dx", solution: "\\frac5{m+14+1}x^{m+14+1}\\ln x - \\frac5{({m+14+1})^2}x^{m+14+1} + C" },
            { level: 3, latex: "2x\\sin(14x) dx", solution: "5(-\\frac{x\\cos(13x)}{m+11} + \\frac{\\sin(13x)}{m+11}^2}) ) + C" },
            { level: 3, latex: "\\ln(x^{m+9}) dx", solution: "x(10\\ln x - 1) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (2^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (4^2)}\\right| + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (8^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (6^2)}\\right| + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (6^2)} dx", solution: "\\frac{1}{m+5}\\arctan\\left(\\frac{x}{m+5}\\right) + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (3^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (5^2)) + C" },
            { level: 5, latex: "(15)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+11}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+11}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+11}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(5)/(x^4 + 1) dx", solution: "\\frac{n+3}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+3}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(10)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+7}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+7}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+7}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(30)/(x^6 + 1) dx", solution: "\\frac{n+27}{3}\\arctan x + \\frac{n+27}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+27}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+27}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col7",
        name: "Collection 7",
        problems: [
            { level: 1, latex: "x^{m+24} dx", solution: "\\frac{1}{m+24+1}x^{m+24+1} + C" },
            { level: 1, latex: "1\\cos(8x) dx", solution: "\\frac4{m+7}\\sin(10x) + C" },
            { level: 1, latex: "4\\sin(13x) dx", solution: "-\\frac4{m+9}\\cos(10x) + C" },
            { level: 1, latex: "5\\cos(24x) dx", solution: "\\frac5{m+23}\\sin(25x) + C" },
            { level: 2, latex: "2x^{m+6} e^{x^{m+6+1}} dx", solution: "\\frac3{m+6+1}e^{x^{m+6+1}} + C" },
            { level: 2, latex: "5x^{m+9} \\sin(x^{m+9+1}) dx", solution: "-\\frac3{m+9+1}\\cos(x^{m+9+1}) + C" },
            { level: 2, latex: "1x^{m+28} \\cos(x^{m+28+1}) dx", solution: "\\frac4{m+28+1}\\sin(x^{m+28+1}) + C" },
            { level: 2, latex: "2x^{m+4} \\cos(x^{m+4+1}) dx", solution: "\\frac1{m+4+1}\\sin(x^{m+4+1}) + C" },
            { level: 3, latex: "2x^{m+7} \\ln x dx", solution: "\\frac4{m+7+1}x^{m+7+1}\\ln x - \\frac4{({m+7+1})^2}x^{m+7+1} + C" },
            { level: 3, latex: "\\ln(x^{m+17}) dx", solution: "x(18\\ln x - 1) + C" },
            { level: 3, latex: "\\ln(x^{m+14}) dx", solution: "x(18\\ln x - 1) + C" },
            { level: 3, latex: "5x^{m+8} \\ln x dx", solution: "\\frac1{m+8+1}x^{m+8+1}\\ln x - \\frac1{({m+8+1})^2}x^{m+8+1} + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (13^2)} dx", solution: "\\frac{1}{m+11}\\arctan\\left(\\frac{x}{m+11}\\right) + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (21^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (21^2)) + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (13^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (15^2)) + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (15^2)} dx", solution: "\\frac{1}{m+14}\\arctan\\left(\\frac{x}{m+14}\\right) + C" },
            { level: 5, latex: "(17)/(x^6 + 1) dx", solution: "\\frac{n+12}{3}\\arctan x + \\frac{n+12}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+12}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+12}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(29)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+25}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+25}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+25}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(30)/(x^6 + 1) dx", solution: "\\frac{n+28}{3}\\arctan x + \\frac{n+28}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+28}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+28}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(14)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+10}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+10}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+10}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col8",
        name: "Collection 8",
        problems: [
            { level: 1, latex: "x^{m+17} dx", solution: "\\frac{1}{m+17+1}x^{m+17+1} + C" },
            { level: 1, latex: "2\\cos(8x) dx", solution: "\\frac4{m+4}\\sin(7x) + C" },
            { level: 1, latex: "3\\cos(14x) dx", solution: "\\frac1{m+11}\\sin(14x) + C" },
            { level: 1, latex: "5\\cos(19x) dx", solution: "\\frac3{m+15}\\sin(17x) + C" },
            { level: 2, latex: "2x^{m+19} \\sin(x^{m+19+1}) dx", solution: "-\\frac2{m+19+1}\\cos(x^{m+19+1}) + C" },
            { level: 2, latex: "5x^{m+1} e^{x^{m+1+1}} dx", solution: "\\frac5{m+1+1}e^{x^{m+1+1}} + C" },
            { level: 2, latex: "2x^{m+11} \\sin(x^{m+11+1}) dx", solution: "-\\frac4{m+11+1}\\cos(x^{m+11+1}) + C" },
            { level: 2, latex: "3x^{m+21} \\sin(x^{m+21+1}) dx", solution: "-\\frac4{m+21+1}\\cos(x^{m+21+1}) + C" },
            { level: 3, latex: "1x^{m+20} \\ln x dx", solution: "\\frac2{m+20+1}x^{m+20+1}\\ln x - \\frac2{({m+20+1})^2}x^{m+20+1} + C" },
            { level: 3, latex: "3x\\cos(19x) dx", solution: "3(\\frac{x\\sin(18x)}{m+17} + \\frac{\\cos(18x)}{m+17}^2}) ) + C" },
            { level: 3, latex: "3x^{m+19} \\ln x dx", solution: "\\frac3{m+19+1}x^{m+19+1}\\ln x - \\frac3{({m+19+1})^2}x^{m+19+1} + C" },
            { level: 3, latex: "3x\\cos(24x) dx", solution: "2(\\frac{x\\sin(23x)}{m+22} + \\frac{\\cos(23x)}{m+22}^2}) ) + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (21^2)} dx", solution: "\\sqrt{x^2 + (23^2)} + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (17^2)} dx", solution: "\\frac{1}{m+15}\\arctan\\left(\\frac{x}{m+15}\\right) + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (6^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (6^2)) + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (8^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (6^2)) + C" },
            { level: 5, latex: "(15)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+14}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+14}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+14}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(34)/(x^4 + 1) dx", solution: "\\frac{n+29}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+29}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(27)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+23}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+23}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+23}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(19)/(x^4 + 1) dx", solution: "\\frac{n+17}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+17}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col9",
        name: "Collection 9",
        problems: [
            { level: 1, latex: "3x^{m+1} dx", solution: "\\frac5{m+1+1}x^{m+1+1} + C" },
            { level: 1, latex: "x^{m+13} dx", solution: "\\frac{1}{m+13+1}x^{m+13+1} + C" },
            { level: 1, latex: "1\\cos(20x) dx", solution: "\\frac5{m+17}\\sin(20x) + C" },
            { level: 1, latex: "5x^{m+10} dx", solution: "\\frac4{m+10+1}x^{m+10+1} + C" },
            { level: 2, latex: "3x^{m+15} \\cos(x^{m+15+1}) dx", solution: "\\frac3{m+15+1}\\sin(x^{m+15+1}) + C" },
            { level: 2, latex: "4x^{m+11} \\cos(x^{m+11+1}) dx", solution: "\\frac1{m+11+1}\\sin(x^{m+11+1}) + C" },
            { level: 2, latex: "4x^{m+8} e^{x^{m+8+1}} dx", solution: "\\frac4{m+8+1}e^{x^{m+8+1}} + C" },
            { level: 2, latex: "3x^{m+11} e^{x^{m+11+1}} dx", solution: "\\frac3{m+11+1}e^{x^{m+11+1}} + C" },
            { level: 3, latex: "5x\\sin(7x) dx", solution: "5(-\\frac{x\\cos(9x)}{m+6} + \\frac{\\sin(9x)}{m+6}^2}) ) + C" },
            { level: 3, latex: "\\ln(x^{m+22}) dx", solution: "x(25\\ln x - 1) + C" },
            { level: 3, latex: "\\ln(x^{m+4}) dx", solution: "x(5\\ln x - 1) + C" },
            { level: 3, latex: "\\ln(x^{m+23}) dx", solution: "x(27\\ln x - 1) + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (19^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (19^2)) + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (21^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (20^2)) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(21^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+18}\\right) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(21^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+19}\\right) + C" },
            { level: 5, latex: "(17)/(x^4 + 1) dx", solution: "\\frac{n+14}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+14}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(12)/(x^6 + 1) dx", solution: "\\frac{n+9}{3}\\arctan x + \\frac{n+9}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+9}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+9}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(17)/(x^4 + 1) dx", solution: "\\frac{n+16}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+16}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(26)/(x^4 + 1) dx", solution: "\\frac{n+23}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+23}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col10",
        name: "Collection 10",
        problems: [
            { level: 1, latex: "3\\cos(12x) dx", solution: "\\frac2{m+10}\\sin(13x) + C" },
            { level: 1, latex: "1\\cos(27x) dx", solution: "\\frac5{m+24}\\sin(25x) + C" },
            { level: 1, latex: "5x^{m+7} dx", solution: "\\frac5{m+7+1}x^{m+7+1} + C" },
            { level: 1, latex: "4\\sin(9x) dx", solution: "-\\frac2{m+5}\\cos(7x) + C" },
            { level: 2, latex: "2x^{m+18} \\sin(x^{m+18+1}) dx", solution: "-\\frac2{m+18+1}\\cos(x^{m+18+1}) + C" },
            { level: 2, latex: "5x^{m+4} e^{x^{m+4+1}} dx", solution: "\\frac3{m+4+1}e^{x^{m+4+1}} + C" },
            { level: 2, latex: "4x^{m+26} e^{x^{m+26+1}} dx", solution: "\\frac5{m+26+1}e^{x^{m+26+1}} + C" },
            { level: 2, latex: "3x^{m+9} e^{x^{m+9+1}} dx", solution: "\\frac5{m+9+1}e^{x^{m+9+1}} + C" },
            { level: 3, latex: "5x\\sin(4x) dx", solution: "5(-\\frac{x\\cos(4x)}{m+3} + \\frac{\\sin(4x)}{m+3}^2}) ) + C" },
            { level: 3, latex: "\\ln(x^{m+3}) dx", solution: "x(6\\ln x - 1) + C" },
            { level: 3, latex: "5x^{m+11} \\ln x dx", solution: "\\frac2{m+11+1}x^{m+11+1}\\ln x - \\frac2{({m+11+1})^2}x^{m+11+1} + C" },
            { level: 3, latex: "5x\\sin(22x) dx", solution: "5(-\\frac{x\\cos(25x)}{m+21} + \\frac{\\sin(25x)}{m+21}^2}) ) + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (8^2)} dx", solution: "\\sqrt{x^2 + (8^2)} + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (3^2)} dx", solution: "\\sqrt{x^2 + (5^2)} + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (13^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (13^2)) + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (3^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (3^2)) + C" },
            { level: 5, latex: "(6)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+1}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+1}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+1}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(3)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+0}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+0}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+0}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(22)/(x^6 + 1) dx", solution: "\\frac{n+17}{3}\\arctan x + \\frac{n+17}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+17}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+17}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(18)/(x^4 + 1) dx", solution: "\\frac{n+13}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+13}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col11",
        name: "Collection 11",
        problems: [
            { level: 1, latex: "2\\sin(15x) dx", solution: "-\\frac4{m+13}\\cos(16x) + C" },
            { level: 1, latex: "x^{m+6} dx", solution: "\\frac{1}{m+6+1}x^{m+6+1} + C" },
            { level: 1, latex: "x^{m+2} dx", solution: "\\frac{1}{m+2+1}x^{m+2+1} + C" },
            { level: 1, latex: "5\\cos(14x) dx", solution: "\\frac2{m+13}\\sin(16x) + C" },
            { level: 2, latex: "\\frac{1}{(8x + 3)} dx", solution: "\\frac{1}{n+4}\\ln|(7x + 2)| + C" },
            { level: 2, latex: "1x^{m+22} e^{x^{m+22+1}} dx", solution: "\\frac5{m+22+1}e^{x^{m+22+1}} + C" },
            { level: 2, latex: "\\frac{1}{(4x + 2)} dx", solution: "\\frac{1}{n+1}\\ln|(3x + 1)| + C" },
            { level: 2, latex: "\\frac{1}{(9x + 2)} dx", solution: "\\frac{1}{n+8}\\ln|(11x + 4)| + C" },
            { level: 3, latex: "1x\\sin(21x) dx", solution: "1(-\\frac{x\\cos(20x)}{m+19} + \\frac{\\sin(20x)}{m+19}^2}) ) + C" },
            { level: 3, latex: "4x\\sin(12x) dx", solution: "3(-\\frac{x\\cos(13x)}{m+9} + \\frac{\\sin(13x)}{m+9}^2}) ) + C" },
            { level: 3, latex: "4x\\cos(13x) dx", solution: "4(\\frac{x\\sin(15x)}{m+11} + \\frac{\\cos(15x)}{m+11}^2}) ) + C" },
            { level: 3, latex: "3x^{m+4} \\ln x dx", solution: "\\frac2{m+4+1}x^{m+4+1}\\ln x - \\frac2{({m+4+1})^2}x^{m+4+1} + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (19^2)} dx", solution: "\\sqrt{x^2 + (17^2)} + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (3^2)} dx", solution: "\\frac{1}{m+1}\\arctan\\left(\\frac{x}{m+1}\\right) + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (12^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (12^2)) + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (2^2)} dx", solution: "\\frac{1}{m}\\arctan\\left(\\frac{x}{m}\\right) + C" },
            { level: 5, latex: "(10)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+8}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+8}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+8}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(5)/(x^6 + 1) dx", solution: "\\frac{n+1}{3}\\arctan x + \\frac{n+1}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+1}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+1}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(24)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+20}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+20}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+20}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(19)/(x^6 + 1) dx", solution: "\\frac{n+15}{3}\\arctan x + \\frac{n+15}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+15}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+15}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col12",
        name: "Collection 12",
        problems: [
            { level: 1, latex: "x^{m+7} dx", solution: "\\frac{1}{m+7+1}x^{m+7+1} + C" },
            { level: 1, latex: "x^{m+18} dx", solution: "\\frac{1}{m+18+1}x^{m+18+1} + C" },
            { level: 1, latex: "1\\sin(16x) dx", solution: "-\\frac3{m+14}\\cos(15x) + C" },
            { level: 1, latex: "1\\sin(23x) dx", solution: "-\\frac5{m+22}\\cos(23x) + C" },
            { level: 2, latex: "2x^{m+24} \\sin(x^{m+24+1}) dx", solution: "-\\frac3{m+24+1}\\cos(x^{m+24+1}) + C" },
            { level: 2, latex: "2x^{m+1} \\sin(x^{m+1+1}) dx", solution: "-\\frac5{m+1+1}\\cos(x^{m+1+1}) + C" },
            { level: 2, latex: "3x^{m+2} \\sin(x^{m+2+1}) dx", solution: "-\\frac2{m+2+1}\\cos(x^{m+2+1}) + C" },
            { level: 2, latex: "\\frac{1}{(10x + 4)} dx", solution: "\\frac{1}{n+7}\\ln|(11x + 3)| + C" },
            { level: 3, latex: "\\ln(x^{m+11}) dx", solution: "x(12\\ln x - 1) + C" },
            { level: 3, latex: "2x^{m+5} \\ln x dx", solution: "\\frac1{m+5+1}x^{m+5+1}\\ln x - \\frac1{({m+5+1})^2}x^{m+5+1} + C" },
            { level: 3, latex: "5x\\cos(1x) dx", solution: "2(\\frac{x\\sin(1x)}{m} + \\frac{\\cos(1x)}{m}^2}) ) + C" },
            { level: 3, latex: "\\ln(x^{m+16}) dx", solution: "x(19\\ln x - 1) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(11^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+9}\\right) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(18^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+14}\\right) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (19^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (20^2)}\\right| + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (19^2)} dx", solution: "\\frac{1}{m+17}\\arctan\\left(\\frac{x}{m+17}\\right) + C" },
            { level: 5, latex: "(8)/(x^6 + 1) dx", solution: "\\frac{n+5}{3}\\arctan x + \\frac{n+5}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+5}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+5}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(27)/(x^4 + 1) dx", solution: "\\frac{n+25}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+25}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(28)/(x^4 + 1) dx", solution: "\\frac{n+27}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+27}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(14)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+9}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+9}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+9}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col13",
        name: "Collection 13",
        problems: [
            { level: 1, latex: "5x^{m+6} dx", solution: "\\frac4{m+6+1}x^{m+6+1} + C" },
            { level: 1, latex: "4\\cos(3x) dx", solution: "\\frac5{m+1}\\sin(5x) + C" },
            { level: 1, latex: "x^{m+12} dx", solution: "\\frac{1}{m+12+1}x^{m+12+1} + C" },
            { level: 1, latex: "x^{m+1} dx", solution: "\\frac{1}{m+1+1}x^{m+1+1} + C" },
            { level: 2, latex: "2x^{m+7} \\sin(x^{m+7+1}) dx", solution: "-\\frac2{m+7+1}\\cos(x^{m+7+1}) + C" },
            { level: 2, latex: "1x^{m+17} \\cos(x^{m+17+1}) dx", solution: "\\frac1{m+17+1}\\sin(x^{m+17+1}) + C" },
            { level: 2, latex: "2x^{m+10} e^{x^{m+10+1}} dx", solution: "\\frac4{m+10+1}e^{x^{m+10+1}} + C" },
            { level: 2, latex: "2x^{m+23} \\sin(x^{m+23+1}) dx", solution: "-\\frac4{m+23+1}\\cos(x^{m+23+1}) + C" },
            { level: 3, latex: "3x\\sin(19x) dx", solution: "5(-\\frac{x\\cos(20x)}{m+16} + \\frac{\\sin(20x)}{m+16}^2}) ) + C" },
            { level: 3, latex: "3x\\sin(10x) dx", solution: "1(-\\frac{x\\cos(12x)}{m+8} + \\frac{\\sin(12x)}{m+8}^2}) ) + C" },
            { level: 3, latex: "1x^{m+2} \\ln x dx", solution: "\\frac3{m+2+1}x^{m+2+1}\\ln x - \\frac3{({m+2+1})^2}x^{m+2+1} + C" },
            { level: 3, latex: "3x\\cos(17x) dx", solution: "5(\\frac{x\\sin(14x)}{m+13} + \\frac{\\cos(14x)}{m+13}^2}) ) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(8^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+5}\\right) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(6^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+3}\\right) + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (15^2)} dx", solution: "\\sqrt{x^2 + (12^2)} + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (15^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (16^2)}\\right| + C" },
            { level: 5, latex: "(10)/(x^4 + 1) dx", solution: "\\frac{n+8}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+8}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(14)/(x^4 + 1) dx", solution: "\\frac{n+10}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+10}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(23)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+18}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+18}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+18}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(3)/(x^4 + 1) dx", solution: "\\frac{n+2}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+2}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col14",
        name: "Collection 14",
        problems: [
            { level: 1, latex: "3\\cos(23x) dx", solution: "\\frac3{m+19}\\sin(21x) + C" },
            { level: 1, latex: "5\\sin(1x) dx", solution: "-\\frac4{m}\\cos(4x) + C" },
            { level: 1, latex: "4\\sin(14x) dx", solution: "-\\frac2{m+12}\\cos(13x) + C" },
            { level: 1, latex: "4\\sin(7x) dx", solution: "-\\frac3{m+4}\\cos(8x) + C" },
            { level: 2, latex: "3x^{m+16} e^{x^{m+16+1}} dx", solution: "\\frac4{m+16+1}e^{x^{m+16+1}} + C" },
            { level: 2, latex: "4x^{m+27} \\sin(x^{m+27+1}) dx", solution: "-\\frac3{m+27+1}\\cos(x^{m+27+1}) + C" },
            { level: 2, latex: "1x^{m+1} \\cos(x^{m+1+1}) dx", solution: "\\frac2{m+1+1}\\sin(x^{m+1+1}) + C" },
            { level: 2, latex: "5x^{m+10} \\sin(x^{m+10+1}) dx", solution: "-\\frac4{m+10+1}\\cos(x^{m+10+1}) + C" },
            { level: 3, latex: "4x\\cos(14x) dx", solution: "5(\\frac{x\\sin(15x)}{m+12} + \\frac{\\cos(15x)}{m+12}^2}) ) + C" },
            { level: 3, latex: "\\ln(x^{m+12}) dx", solution: "x(14\\ln x - 1) + C" },
            { level: 3, latex: "\\ln(x^{m+1}) dx", solution: "x(5\\ln x - 1) + C" },
            { level: 3, latex: "4x^{m+10} \\ln x dx", solution: "\\frac3{m+10+1}x^{m+10+1}\\ln x - \\frac3{({m+10+1})^2}x^{m+10+1} + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (4^2)} dx", solution: "\\sqrt{x^2 + (5^2)} + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (9^2)} dx", solution: "\\frac{1}{m+7}\\arctan\\left(\\frac{x}{m+7}\\right) + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (7^2)} dx", solution: "\\sqrt{x^2 + (7^2)} + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (21^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (21^2)) + C" },
            { level: 5, latex: "(7)/(x^4 + 1) dx", solution: "\\frac{n+4}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+4}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(15)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+13}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+13}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+13}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(14)/(x^4 + 1) dx", solution: "\\frac{n+11}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+11}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(4)/(x^6 + 1) dx", solution: "\\frac{n+3}{3}\\arctan x + \\frac{n+3}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+3}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+3}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col15",
        name: "Collection 15",
        problems: [
            { level: 1, latex: "4x^{m+9} dx", solution: "\\frac4{m+9+1}x^{m+9+1} + C" },
            { level: 1, latex: "5x^{m+14} dx", solution: "\\frac5{m+14+1}x^{m+14+1} + C" },
            { level: 1, latex: "2x^{m+24} dx", solution: "\\frac3{m+24+1}x^{m+24+1} + C" },
            { level: 1, latex: "3\\cos(23x) dx", solution: "\\frac4{m+22}\\sin(23x) + C" },
            { level: 2, latex: "\\frac{1}{(5x + 3)} dx", solution: "\\frac{1}{n+2}\\ln|(7x + 2)| + C" },
            { level: 2, latex: "5x^{m+26} \\cos(x^{m+26+1}) dx", solution: "\\frac3{m+26+1}\\sin(x^{m+26+1}) + C" },
            { level: 2, latex: "4x^{m} \\sin(x^{m+1}) dx", solution: "-\\frac1{m+1}\\cos(x^{m+1}) + C" },
            { level: 2, latex: "3x^{m+27} e^{x^{m+27+1}} dx", solution: "\\frac5{m+27+1}e^{x^{m+27+1}} + C" },
            { level: 3, latex: "2x\\sin(16x) dx", solution: "3(-\\frac{x\\cos(14x)}{m+12} + \\frac{\\sin(14x)}{m+12}^2}) ) + C" },
            { level: 3, latex: "\\ln(x^{m+7}) dx", solution: "x(10\\ln x - 1) + C" },
            { level: 3, latex: "3x^{m+6} \\ln x dx", solution: "\\frac2{m+6+1}x^{m+6+1}\\ln x - \\frac2{({m+6+1})^2}x^{m+6+1} + C" },
            { level: 3, latex: "3x\\cos(9x) dx", solution: "3(\\frac{x\\sin(7x)}{m+5} + \\frac{\\cos(7x)}{m+5}^2}) ) + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (11^2)} dx", solution: "\\sqrt{x^2 + (8^2)} + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (20^2)} dx", solution: "\\frac{1}{m+18}\\arctan\\left(\\frac{x}{m+18}\\right) + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (10^2)} dx", solution: "\\frac{1}{m+8}\\arctan\\left(\\frac{x}{m+8}\\right) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(9^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+8}\\right) + C" },
            { level: 5, latex: "(31)/(x^6 + 1) dx", solution: "\\frac{n+30}{3}\\arctan x + \\frac{n+30}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+30}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+30}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(26)/(x^6 + 1) dx", solution: "\\frac{n+23}{3}\\arctan x + \\frac{n+23}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+23}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+23}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(21)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+17}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+17}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+17}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(27)/(x^6 + 1) dx", solution: "\\frac{n+24}{3}\\arctan x + \\frac{n+24}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+24}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+24}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col16",
        name: "Collection 16",
        problems: [
            { level: 1, latex: "3x^{m+21} dx", solution: "\\frac5{m+21+1}x^{m+21+1} + C" },
            { level: 1, latex: "3\\cos(21x) dx", solution: "\\frac4{m+18}\\sin(20x) + C" },
            { level: 1, latex: "2\\sin(12x) dx", solution: "-\\frac5{m+11}\\cos(12x) + C" },
            { level: 1, latex: "4x^{m+19} dx", solution: "\\frac4{m+19+1}x^{m+19+1} + C" },
            { level: 2, latex: "3x^{m+20} \\cos(x^{m+20+1}) dx", solution: "\\frac5{m+20+1}\\sin(x^{m+20+1}) + C" },
            { level: 2, latex: "1x^{m+28} \\sin(x^{m+28+1}) dx", solution: "-\\frac1{m+28+1}\\cos(x^{m+28+1}) + C" },
            { level: 2, latex: "3x^{m+7} e^{x^{m+7+1}} dx", solution: "\\frac3{m+7+1}e^{x^{m+7+1}} + C" },
            { level: 2, latex: "1x^{m+19} \\cos(x^{m+19+1}) dx", solution: "\\frac3{m+19+1}\\sin(x^{m+19+1}) + C" },
            { level: 3, latex: "5x\\sin(21x) dx", solution: "4(-\\frac{x\\cos(20x)}{m+17} + \\frac{\\sin(20x)}{m+17}^2}) ) + C" },
            { level: 3, latex: "5x\\cos(11x) dx", solution: "2(\\frac{x\\sin(11x)}{m+10} + \\frac{\\cos(11x)}{m+10}^2}) ) + C" },
            { level: 3, latex: "3x\\sin(20x) dx", solution: "3(-\\frac{x\\cos(22x)}{m+18} + \\frac{\\sin(22x)}{m+18}^2}) ) + C" },
            { level: 3, latex: "1x\\sin(17x) dx", solution: "5(-\\frac{x\\cos(17x)}{m+13} + \\frac{\\sin(17x)}{m+13}^2}) ) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(20^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+17}\\right) + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (5^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (4^2)) + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (3^2)} dx", solution: "\\frac{1}{m+2}\\arctan\\left(\\frac{x}{m+2}\\right) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (15^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (17^2)}\\right| + C" },
            { level: 5, latex: "(26)/(x^4 + 1) dx", solution: "\\frac{n+22}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+22}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(35)/(x^4 + 1) dx", solution: "\\frac{n+33}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+33}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(32)/(x^6 + 1) dx", solution: "\\frac{n+29}{3}\\arctan x + \\frac{n+29}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+29}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+29}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(11)/(x^6 + 1) dx", solution: "\\frac{n+7}{3}\\arctan x + \\frac{n+7}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+7}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+7}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col17",
        name: "Collection 17",
        problems: [
            { level: 1, latex: "x^{m+21} dx", solution: "\\frac{1}{m+21+1}x^{m+21+1} + C" },
            { level: 1, latex: "4\\sin(22x) dx", solution: "-\\frac1{m+20}\\cos(21x) + C" },
            { level: 1, latex: "2\\sin(27x) dx", solution: "-\\frac4{m+24}\\cos(28x) + C" },
            { level: 1, latex: "2\\sin(17x) dx", solution: "-\\frac3{m+15}\\cos(16x) + C" },
            { level: 2, latex: "1x^{m+8} \\cos(x^{m+8+1}) dx", solution: "\\frac5{m+8+1}\\sin(x^{m+8+1}) + C" },
            { level: 2, latex: "1x^{m+20} \\sin(x^{m+20+1}) dx", solution: "-\\frac3{m+20+1}\\cos(x^{m+20+1}) + C" },
            { level: 2, latex: "4x^{m+4} \\sin(x^{m+4+1}) dx", solution: "-\\frac5{m+4+1}\\cos(x^{m+4+1}) + C" },
            { level: 2, latex: "3x^{m+2} e^{x^{m+2+1}} dx", solution: "\\frac4{m+2+1}e^{x^{m+2+1}} + C" },
            { level: 3, latex: "2x^{m+9} \\ln x dx", solution: "\\frac3{m+9+1}x^{m+9+1}\\ln x - \\frac3{({m+9+1})^2}x^{m+9+1} + C" },
            { level: 3, latex: "2x\\cos(19x) dx", solution: "3(\\frac{x\\sin(18x)}{m+16} + \\frac{\\cos(18x)}{m+16}^2}) ) + C" },
            { level: 3, latex: "\\ln(x^{m}) dx", solution: "x(3\\ln x - 1) + C" },
            { level: 3, latex: "5x\\cos(20x) dx", solution: "4(\\frac{x\\sin(21x)}{m+19} + \\frac{\\cos(21x)}{m+19}^2}) ) + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (20^2)} dx", solution: "\\sqrt{x^2 + (19^2)} + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (19^2)} dx", solution: "\\sqrt{x^2 + (22^2)} + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(3^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+1}\\right) + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (11^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (11^2)) + C" },
            { level: 5, latex: "(25)/(x^6 + 1) dx", solution: "\\frac{n+21}{3}\\arctan x + \\frac{n+21}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+21}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+21}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(22)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+19}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+19}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+19}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(34)/(x^6 + 1) dx", solution: "\\frac{n+32}{3}\\arctan x + \\frac{n+32}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+32}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+32}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(5)/(x^6 + 1) dx", solution: "\\frac{n+0}{3}\\arctan x + \\frac{n+0}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+0}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col18",
        name: "Collection 18",
        problems: [
            { level: 1, latex: "x^{m+23} dx", solution: "\\frac{1}{m+23+1}x^{m+23+1} + C" },
            { level: 1, latex: "x^{m+22} dx", solution: "\\frac{1}{m+22+1}x^{m+22+1} + C" },
            { level: 1, latex: "3x^{m+23} dx", solution: "\\frac4{m+23+1}x^{m+23+1} + C" },
            { level: 1, latex: "1\\cos(16x) dx", solution: "\\frac5{m+14}\\sin(15x) + C" },
            { level: 2, latex: "2x^{m+19} e^{x^{m+19+1}} dx", solution: "\\frac2{m+19+1}e^{x^{m+19+1}} + C" },
            { level: 2, latex: "1x^{m+22} \\sin(x^{m+22+1}) dx", solution: "-\\frac1{m+22+1}\\cos(x^{m+22+1}) + C" },
            { level: 2, latex: "4x^{m+9} \\cos(x^{m+9+1}) dx", solution: "\\frac4{m+9+1}\\sin(x^{m+9+1}) + C" },
            { level: 2, latex: "5x^{m+17} \\sin(x^{m+17+1}) dx", solution: "-\\frac2{m+17+1}\\cos(x^{m+17+1}) + C" },
            { level: 3, latex: "5x\\cos(22x) dx", solution: "1(\\frac{x\\sin(21x)}{m+18} + \\frac{\\cos(21x)}{m+18}^2}) ) + C" },
            { level: 3, latex: "3x\\cos(22x) dx", solution: "2(\\frac{x\\sin(23x)}{m+21} + \\frac{\\cos(23x)}{m+21}^2}) ) + C" },
            { level: 3, latex: "3x\\cos(10x) dx", solution: "5(\\frac{x\\sin(9x)}{m+7} + \\frac{\\cos(9x)}{m+7}^2}) ) + C" },
            { level: 3, latex: "3x\\sin(26x) dx", solution: "2(-\\frac{x\\cos(25x)}{m+22} + \\frac{\\sin(25x)}{m+22}^2}) ) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(3^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m}\\right) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (20^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (20^2)}\\right| + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (20^2)} dx", solution: "\\frac{1}{m+16}\\arctan\\left(\\frac{x}{m+16}\\right) + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (15^2)} dx", solution: "\\sqrt{x^2 + (14^2)} + C" },
            { level: 5, latex: "(27)/(x^4 + 1) dx", solution: "\\frac{n+24}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+24}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(11)/(x^4 + 1) dx", solution: "\\frac{n+9}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+9}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(24)/(x^6 + 1) dx", solution: "\\frac{n+22}{3}\\arctan x + \\frac{n+22}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+22}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+22}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(1)/(x^4 + 1) dx", solution: "\\frac{n+0}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+0}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col19",
        name: "Collection 19",
        problems: [
            { level: 1, latex: "4x^{m} dx", solution: "\\frac4{m+1}x^{m+1} + C" },
            { level: 1, latex: "4\\cos(15x) dx", solution: "\\frac1{m+12}\\sin(13x) + C" },
            { level: 1, latex: "1\\sin(3x) dx", solution: "-\\frac1{m+1}\\cos(3x) + C" },
            { level: 1, latex: "2\\cos(1x) dx", solution: "\\frac3{m}\\sin(4x) + C" },
            { level: 2, latex: "5x^{m+8} \\sin(x^{m+8+1}) dx", solution: "-\\frac1{m+8+1}\\cos(x^{m+8+1}) + C" },
            { level: 2, latex: "4x^{m+13} e^{x^{m+13+1}} dx", solution: "\\frac3{m+13+1}e^{x^{m+13+1}} + C" },
            { level: 2, latex: "5x^{m+10} \\cos(x^{m+10+1}) dx", solution: "\\frac4{m+10+1}\\sin(x^{m+10+1}) + C" },
            { level: 2, latex: "4x^{m+13} \\cos(x^{m+13+1}) dx", solution: "\\frac5{m+13+1}\\sin(x^{m+13+1}) + C" },
            { level: 3, latex: "1x\\sin(27x) dx", solution: "1(-\\frac{x\\cos(25x)}{m+23} + \\frac{\\sin(25x)}{m+23}^2}) ) + C" },
            { level: 3, latex: "1x^{m+13} \\ln x dx", solution: "\\frac3{m+13+1}x^{m+13+1}\\ln x - \\frac3{({m+13+1})^2}x^{m+13+1} + C" },
            { level: 3, latex: "1x^{m+1} \\ln x dx", solution: "\\frac1{m+1+1}x^{m+1+1}\\ln x - \\frac1{({m+1+1})^2}x^{m+1+1} + C" },
            { level: 3, latex: "\\ln(x^{m+6}) dx", solution: "x(10\\ln x - 1) + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (18^2)} dx", solution: "\\sqrt{x^2 + (15^2)} + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (7^2)} dx", solution: "\\frac{1}{m+6}\\arctan\\left(\\frac{x}{m+6}\\right) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (8^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (9^2)}\\right| + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(12^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+11}\\right) + C" },
            { level: 5, latex: "(20)/(x^4 + 1) dx", solution: "\\frac{n+15}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+15}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(20)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+15}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+15}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+15}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(10)/(x^4 + 1) dx", solution: "\\frac{n+7}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+7}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(25)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+22}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+22}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+22}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col20",
        name: "Collection 20",
        problems: [
            { level: 1, latex: "3x^{m+12} dx", solution: "\\frac4{m+12+1}x^{m+12+1} + C" },
            { level: 1, latex: "4x^{m+16} dx", solution: "\\frac2{m+16+1}x^{m+16+1} + C" },
            { level: 1, latex: "5\\sin(24x) dx", solution: "-\\frac5{m+23}\\cos(27x) + C" },
            { level: 1, latex: "5\\sin(8x) dx", solution: "-\\frac5{m+7}\\cos(9x) + C" },
            { level: 2, latex: "3x^{m+12} \\sin(x^{m+12+1}) dx", solution: "-\\frac4{m+12+1}\\cos(x^{m+12+1}) + C" },
            { level: 2, latex: "2x^{m+26} \\sin(x^{m+26+1}) dx", solution: "-\\frac2{m+26+1}\\cos(x^{m+26+1}) + C" },
            { level: 2, latex: "1x^{m+5} e^{x^{m+5+1}} dx", solution: "\\frac5{m+5+1}e^{x^{m+5+1}} + C" },
            { level: 2, latex: "1x^{m+16} \\sin(x^{m+16+1}) dx", solution: "-\\frac3{m+16+1}\\cos(x^{m+16+1}) + C" },
            { level: 3, latex: "5x^{m+22} \\ln x dx", solution: "\\frac4{m+22+1}x^{m+22+1}\\ln x - \\frac4{({m+22+1})^2}x^{m+22+1} + C" },
            { level: 3, latex: "\\ln(x^{m+5}) dx", solution: "x(8\\ln x - 1) + C" },
            { level: 3, latex: "3x^{m+3} \\ln x dx", solution: "\\frac2{m+3+1}x^{m+3+1}\\ln x - \\frac2{({m+3+1})^2}x^{m+3+1} + C" },
            { level: 3, latex: "4x\\sin(18x) dx", solution: "5(-\\frac{x\\cos(15x)}{m+14} + \\frac{\\sin(15x)}{m+14}^2}) ) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (11^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (13^2)}\\right| + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (20^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (17^2)) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(11^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+7}\\right) + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (17^2)} dx", solution: "\\frac{1}{m+13}\\arctan\\left(\\frac{x}{m+13}\\right) + C" },
            { level: 5, latex: "(7)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+6}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+6}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+6}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(4)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+2}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+2}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+2}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(17)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+12}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+12}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+12}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(29)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+27}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+27}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+27}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col21",
        name: "Collection 21",
        problems: [
            { level: 1, latex: "3x^{m+3} dx", solution: "\\frac1{m+3+1}x^{m+3+1} + C" },
            { level: 1, latex: "4\\sin(10x) dx", solution: "-\\frac3{m+6}\\cos(7x) + C" },
            { level: 1, latex: "x^{m+10} dx", solution: "\\frac{1}{m+10+1}x^{m+10+1} + C" },
            { level: 1, latex: "1\\cos(5x) dx", solution: "\\frac4{m+2}\\sin(4x) + C" },
            { level: 2, latex: "5x^{m+16} \\cos(x^{m+16+1}) dx", solution: "\\frac1{m+16+1}\\sin(x^{m+16+1}) + C" },
            { level: 2, latex: "2x^{m+12} \\cos(x^{m+12+1}) dx", solution: "\\frac3{m+12+1}\\sin(x^{m+12+1}) + C" },
            { level: 2, latex: "1x^{m+23} \\cos(x^{m+23+1}) dx", solution: "\\frac1{m+23+1}\\sin(x^{m+23+1}) + C" },
            { level: 2, latex: "\\frac{1}{(10x + 1)} dx", solution: "\\frac{1}{n+6}\\ln|(11x + 4)| + C" },
            { level: 3, latex: "\\ln(x^{m+8}) dx", solution: "x(12\\ln x - 1) + C" },
            { level: 3, latex: "\\ln(x^{m+20}) dx", solution: "x(21\\ln x - 1) + C" },
            { level: 3, latex: "\\ln(x^{m+10}) dx", solution: "x(11\\ln x - 1) + C" },
            { level: 3, latex: "\\ln(x^{m+18}) dx", solution: "x(21\\ln x - 1) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(8^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+6}\\right) + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (13^2)} dx", solution: "\\sqrt{x^2 + (16^2)} + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (10^2)} dx", solution: "\\sqrt{x^2 + (9^2)} + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (7^2)} dx", solution: "\\frac{1}{m+3}\\arctan\\left(\\frac{x}{m+3}\\right) + C" },
            { level: 5, latex: "(34)/(x^6 + 1) dx", solution: "\\frac{n+31}{3}\\arctan x + \\frac{n+31}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+31}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+31}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(12)/(x^6 + 1) dx", solution: "\\frac{n+11}{3}\\arctan x + \\frac{n+11}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+11}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+11}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(20)/(x^6 + 1) dx", solution: "\\frac{n+18}{3}\\arctan x + \\frac{n+18}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+18}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+18}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(31)/(x^4 + 1) dx", solution: "\\frac{n+26}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+26}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col22",
        name: "Collection 22",
        problems: [
            { level: 1, latex: "1x^{m+18} dx", solution: "\\frac3{m+18+1}x^{m+18+1} + C" },
            { level: 1, latex: "2\\sin(6x) dx", solution: "-\\frac5{m+3}\\cos(5x) + C" },
            { level: 1, latex: "4\\cos(7x) dx", solution: "\\frac2{m+5}\\sin(8x) + C" },
            { level: 1, latex: "2\\cos(10x) dx", solution: "\\frac2{m+9}\\sin(13x) + C" },
            { level: 2, latex: "3x^{m+13} \\sin(x^{m+13+1}) dx", solution: "-\\frac4{m+13+1}\\cos(x^{m+13+1}) + C" },
            { level: 2, latex: "1x^{m+12} e^{x^{m+12+1}} dx", solution: "\\frac5{m+12+1}e^{x^{m+12+1}} + C" },
            { level: 2, latex: "4x^{m+3} \\sin(x^{m+3+1}) dx", solution: "-\\frac1{m+3+1}\\cos(x^{m+3+1}) + C" },
            { level: 2, latex: "\\frac{1}{(7x + 1)} dx", solution: "\\frac{1}{n+5}\\ln|(8x + 4)| + C" },
            { level: 3, latex: "4x\\sin(3x) dx", solution: "5(-\\frac{x\\cos(1x)}{m} + \\frac{\\sin(1x)}{m}^2}) ) + C" },
            { level: 3, latex: "5x\\cos(7x) dx", solution: "5(\\frac{x\\sin(5x)}{m+4} + \\frac{\\cos(5x)}{m+4}^2}) ) + C" },
            { level: 3, latex: "3x\\sin(9x) dx", solution: "1(-\\frac{x\\cos(7x)}{m+5} + \\frac{\\sin(7x)}{m+5}^2}) ) + C" },
            { level: 3, latex: "5x^{m+17} \\ln x dx", solution: "\\frac2{m+17+1}x^{m+17+1}\\ln x - \\frac2{({m+17+1})^2}x^{m+17+1} + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(5^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+4}\\right) + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (10^2)} dx", solution: "\\frac{1}{m+9}\\arctan\\left(\\frac{x}{m+9}\\right) + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (5^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (6^2)) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(19^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+15}\\right) + C" },
            { level: 5, latex: "(17)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+16}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+16}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+16}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(26)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+21}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+21}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+21}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(21)/(x^4 + 1) dx", solution: "\\frac{n+20}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+20}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(32)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+28}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+28}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+28}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col23",
        name: "Collection 23",
        problems: [
            { level: 1, latex: "1\\cos(9x) dx", solution: "\\frac1{m+8}\\sin(9x) + C" },
            { level: 1, latex: "x^{m+9} dx", solution: "\\frac{1}{m+9+1}x^{m+9+1} + C" },
            { level: 1, latex: "3\\cos(24x) dx", solution: "\\frac2{m+20}\\sin(21x) + C" },
            { level: 1, latex: "x^{m+15} dx", solution: "\\frac{1}{m+15+1}x^{m+15+1} + C" },
            { level: 2, latex: "\\frac{1}{(12x + 3)} dx", solution: "\\frac{1}{n+9}\\ln|(14x + 1)| + C" },
            { level: 2, latex: "4x^{m+2} \\cos(x^{m+2+1}) dx", solution: "\\frac4{m+2+1}\\sin(x^{m+2+1}) + C" },
            { level: 2, latex: "4x^{m+15} \\sin(x^{m+15+1}) dx", solution: "-\\frac5{m+15+1}\\cos(x^{m+15+1}) + C" },
            { level: 2, latex: "4x^{m+18} \\cos(x^{m+18+1}) dx", solution: "\\frac4{m+18+1}\\sin(x^{m+18+1}) + C" },
            { level: 3, latex: "4x\\cos(7x) dx", solution: "3(\\frac{x\\sin(7x)}{m+3} + \\frac{\\cos(7x)}{m+3}^2}) ) + C" },
            { level: 3, latex: "1x\\sin(9x) dx", solution: "4(-\\frac{x\\cos(9x)}{m+7} + \\frac{\\sin(9x)}{m+7}^2}) ) + C" },
            { level: 3, latex: "\\ln(x^{m+15}) dx", solution: "x(18\\ln x - 1) + C" },
            { level: 3, latex: "2x^{m+15} \\ln x dx", solution: "\\frac1{m+15+1}x^{m+15+1}\\ln x - \\frac1{({m+15+1})^2}x^{m+15+1} + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (12^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (12^2)) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{(20^2 - x^2)} dx", solution: "\\arcsin\\left(\\frac{x}{m+16}\\right) + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (10^2)} dx", solution: "\\sqrt{x^2 + (12^2)} + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (14^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (12^2)) + C" },
            { level: 5, latex: "(8)/(x^6 + 1) dx", solution: "\\frac{n+4}{3}\\arctan x + \\frac{n+4}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+4}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+4}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(30)/(x^6 + 1) dx", solution: "\\frac{n+25}{3}\\arctan x + \\frac{n+25}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+25}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+25}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(33)/(x^4 + 1) dx", solution: "\\frac{n+30}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+30}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(31)/(x^4 - x^2 + 1) dx", solution: "\\frac{n+26}{2}\\arctan(2x - \\sqrt{3}) + \\frac{n+26}{2}\\arctan(2x + \\sqrt{3}) + \\frac{n+26}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col24",
        name: "Collection 24",
        problems: [
            { level: 1, latex: "3x^{m+4} dx", solution: "\\frac4{m+4+1}x^{m+4+1} + C" },
            { level: 1, latex: "3\\sin(21x) dx", solution: "-\\frac3{m+17}\\cos(19x) + C" },
            { level: 1, latex: "x^{m+19} dx", solution: "\\frac{1}{m+19+1}x^{m+19+1} + C" },
            { level: 1, latex: "x^{m+11} dx", solution: "\\frac{1}{m+11+1}x^{m+11+1} + C" },
            { level: 2, latex: "5x^{m+5} \\sin(x^{m+5+1}) dx", solution: "-\\frac2{m+5+1}\\cos(x^{m+5+1}) + C" },
            { level: 2, latex: "2x^{m+25} e^{x^{m+25+1}} dx", solution: "\\frac2{m+25+1}e^{x^{m+25+1}} + C" },
            { level: 2, latex: "4x^{m+29} e^{x^{m+29+1}} dx", solution: "\\frac3{m+29+1}e^{x^{m+29+1}} + C" },
            { level: 2, latex: "4x^{m+25} \\sin(x^{m+25+1}) dx", solution: "-\\frac4{m+25+1}\\cos(x^{m+25+1}) + C" },
            { level: 3, latex: "4x\\cos(11x) dx", solution: "5(\\frac{x\\sin(10x)}{m+8} + \\frac{\\cos(10x)}{m+8}^2}) ) + C" },
            { level: 3, latex: "3x\\cos(5x) dx", solution: "3(\\frac{x\\sin(5x)}{m+2} + \\frac{\\cos(5x)}{m+2}^2}) ) + C" },
            { level: 3, latex: "2x\\sin(25x) dx", solution: "5(-\\frac{x\\cos(28x)}{m+24} + \\frac{\\sin(28x)}{m+24}^2}) ) + C" },
            { level: 3, latex: "4x\\sin(4x) dx", solution: "4(-\\frac{x\\cos(5x)}{m+1} + \\frac{\\sin(5x)}{m+1}^2}) ) + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (3^2)} dx", solution: "\\sqrt{x^2 + (1^2)} + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (8^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (8^2)}\\right| + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (20^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (19^2)}\\right| + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (8^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (8^2)}\\right| + C" },
            { level: 5, latex: "(10)/(x^6 + 1) dx", solution: "\\frac{n+8}{3}\\arctan x + \\frac{n+8}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+8}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+8}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(30)/(x^4 + 1) dx", solution: "\\frac{n+28}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+28}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(15)/(x^6 + 1) dx", solution: "\\frac{n+13}{3}\\arctan x + \\frac{n+13}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+13}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+13}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(20)/(x^6 + 1) dx", solution: "\\frac{n+16}{3}\\arctan x + \\frac{n+16}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+16}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+16}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
        ]
    },
    {
        id: "col25",
        name: "Collection 25",
        problems: [
            { level: 1, latex: "5\\sin(25x) dx", solution: "-\\frac4{m+21}\\cos(24x) + C" },
            { level: 1, latex: "3x^{m+17} dx", solution: "\\frac2{m+17+1}x^{m+17+1} + C" },
            { level: 1, latex: "5\\sin(21x) dx", solution: "-\\frac2{m+18}\\cos(21x) + C" },
            { level: 1, latex: "x^{m+4} dx", solution: "\\frac{1}{m+4+1}x^{m+4+1} + C" },
            { level: 2, latex: "4x^{m+20} e^{x^{m+20+1}} dx", solution: "\\frac3{m+20+1}e^{x^{m+20+1}} + C" },
            { level: 2, latex: "1x^{m+24} e^{x^{m+24+1}} dx", solution: "\\frac1{m+24+1}e^{x^{m+24+1}} + C" },
            { level: 2, latex: "3x^{m+7} \\cos(x^{m+7+1}) dx", solution: "\\frac2{m+7+1}\\sin(x^{m+7+1}) + C" },
            { level: 2, latex: "\\frac{1}{(8x + 3)} dx", solution: "\\frac{1}{n+3}\\ln|(8x + 1)| + C" },
            { level: 3, latex: "1x\\cos(26x) dx", solution: "1(\\frac{x\\sin(24x)}{m+23} + \\frac{\\cos(24x)}{m+23}^2}) ) + C" },
            { level: 3, latex: "3x\\cos(18x) dx", solution: "4(\\frac{x\\sin(16x)}{m+15} + \\frac{\\cos(16x)}{m+15}^2}) ) + C" },
            { level: 3, latex: "1x^{m+24} \\ln x dx", solution: "\\frac2{m+24+1}x^{m+24+1}\\ln x - \\frac2{({m+24+1})^2}x^{m+24+1} + C" },
            { level: 3, latex: "5x^{m+18} \\ln x dx", solution: "\\frac3{m+18+1}x^{m+18+1}\\ln x - \\frac3{({m+18+1})^2}x^{m+18+1} + C" },
            { level: 4, latex: "\\frac{1}{x^2 + (16^2)} dx", solution: "\\frac{1}{m+12}\\arctan\\left(\\frac{x}{m+12}\\right) + C" },
            { level: 4, latex: "\\frac{x}{x^2 + (14^2)} dx", solution: "\\frac{1}{2}\\ln(x^2 + (14^2)) + C" },
            { level: 4, latex: "\\frac{1}{\\sqrt{x^2 + (4^2)} dx", solution: "\\ln\\left|x + \\sqrt{x^2 + (4^2)}\\right| + C" },
            { level: 4, latex: "\\frac{x}{\\sqrt{x^2 + (19^2)} dx", solution: "\\sqrt{x^2 + (18^2)} + C" },
            { level: 5, latex: "(7)/(x^6 + 1) dx", solution: "\\frac{n+6}{3}\\arctan x + \\frac{n+6}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+6}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+6}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(24)/(x^6 + 1) dx", solution: "\\frac{n+20}{3}\\arctan x + \\frac{n+20}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+20}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+20}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
            { level: 5, latex: "(24)/(x^4 + 1) dx", solution: "\\frac{n+19}{2\\sqrt{2}\\arctan\\left(\\frac{x^2 - 1}{\\sqrt{2} x}\\right) + \\frac{n+19}{4\\sqrt{2}\\ln\\left|\\frac{x^2 + \\sqrt{2} x + 1}{x^2 - \\sqrt{2} x + 1}\\right| + C" },
            { level: 5, latex: "(5)/(x^6 + 1) dx", solution: "\\frac{n+2}{3}\\arctan x + \\frac{n+2}{6}\\arctan(2x - \\sqrt{3}) + \\frac{n+2}{6}\\arctan(2x + \\sqrt{3}) + \\frac{n+2}\\sqrt{3}{12}\\ln\\left|\\frac{x^2 + \\sqrt{3} x + 1}{x^2 - \\sqrt{3} x + 1}\\right| + C" },
        ]
    },
];
