
import json
import codecs

vocab = [
    # Passage 1
    {'en': 'experiment', 'ko': '실험, 실험하다'},
    {'en': 'produce', 'ko': '생산하다, 낳다'},
    {'en': 'result', 'ko': '결과, 초래하다'},
    {'en': 'occur', 'ko': '발생하다, 일어나다'},
    {'en': 'purely', 'ko': '순전히, 전적으로'},
    {'en': 'chance', 'ko': '우연, 기회'},
    {'en': 'duplicate', 'ko': '복제하다, 되풀이하다'},
    {'en': 'therefore', 'ko': '그러므로, 따라서'},
    {'en': 'accept', 'ko': '받아들이다, 인정하다'},
    {'en': 'hypothesis', 'ko': '가설'},
    {'en': 'researcher', 'ko': '연구자'},
    {'en': 'repeat', 'ko': '반복하다'},
    {'en': 'several', 'ko': '몇몇의, 여러'},
    {'en': 'guarantee', 'ko': '보장하다'},
    {'en': 'valid', 'ko': '타당한, 유효한'},
    {'en': 'separately', 'ko': '별도로, 독립적으로'},
    {'en': 'essentially', 'ko': '본질적으로, 기본적으로'},
    {'en': 'alternative', 'ko': '대안적인, 대체의'},
    {'en': 'conduct', 'ko': '수행하다, 지휘하다'},
    {'en': 'ensure', 'ko': '확실하게 하다, 보장하다'},
    {'en': 'variable', 'ko': '변수, 변하기 쉬운'},
    {'en': 'overlook', 'ko': '간과하다, 못 보고 넘어가다'},
    {'en': 'approach', 'ko': '접근법, 다가가다'},
    {'en': 'disprove', 'ko': '틀렸음을 입증하다'},
    {'en': 'accurate', 'ko': '정확한'},
    {'en': 'acceptance', 'ko': '수용, 용인'},
    {'en': 'subject to', 'ko': '~의 대상이 되는, ~하기 쉬운'},
    {'en': 'aim', 'ko': '목표, 겨냥하다'},
    {'en': 'achieve', 'ko': '성취하다, 얻다'},
    {'en': 'explanation', 'ko': '설명'},
    {'en': 'phenomenon', 'ko': '현상'},
    {'en': 'investigate', 'ko': '조사하다, 연구하다'},
    
    # Passage 2
    {'en': 'withhold', 'ko': '보류하다, 억제하다'},
    {'en': 'actively', 'ko': '적극적으로'},
    {'en': 'seek', 'ko': '추구하다, 찾다'},
    {'en': 'general', 'ko': '일반적인, 전반적인'},
    {'en': 'antipathy', 'ko': '반감, 혐오'},
    {'en': 'toward', 'ko': '~을 향하여, ~에 대하여'},
    {'en': 'deny', 'ko': '부정하다, 부인하다'},
    {'en': 'appear', 'ko': '~처럼 보이다, 나타나다'},
    {'en': 'hunger', 'ko': '갈망하다, 굶주리다'},
    {'en': 'engage', 'ko': '관여하다, 종사하다'},
    {'en': 'machination', 'ko': '음모, 모략'},
    {'en': 'secretly', 'ko': '비밀리에'},
    {'en': 'democratic', 'ko': '민주주의의'},
    {'en': 'political', 'ko': '정치의'},
    {'en': 'system', 'ko': '체제, 시스템'},
    {'en': 'contain', 'ko': '포함하다, 억제하다'},
    {'en': 'check', 'ko': '견제하다, 확인하다'},
    {'en': 'specify', 'ko': '명시하다, 구체화하다'},
    {'en': 'measure', 'ko': '조치, 측정하다'},
    {'en': 'distribute', 'ko': '분배하다, 나누어주다'},
    {'en': 'prevent', 'ko': '예방하다, 막다'},
    {'en': 'absolute', 'ko': '절대적인'},
    {'en': 'concentrate', 'ko': '집중하다'},
    {'en': 'founder', 'ko': '설립자, 창립자'},
    {'en': 'clash', 'ko': '충돌하다'},
    {'en': 'constitutional', 'ko': '헌법의'},
    {'en': 'establish', 'ko': '설립하다, 확립하다'},
    {'en': 'mechanism', 'ko': '기제, 기계 장치'},
    {'en': 'branch', 'ko': '부서, 나뭇가지'},
    {'en': 'government', 'ko': '정부'},
    {'en': 'protect', 'ko': '보호하다'},
    {'en': 'interest', 'ko': '이익, 관심'},
    {'en': 'minority', 'ko': '소수, 소수 민족'},
    {'en': 'majority', 'ko': '다수, 대다수'},
    {'en': 'individual', 'ko': '개인의, 개인'},
    {'en': 'abridge', 'ko': '요약하다, 한정하다'},

    # Passage 3
    {'en': 'requirement', 'ko': '요건, 필요조건'},
    {'en': 'negative', 'ko': '부정적인'},
    {'en': 'emotion', 'ko': '감정'},
    {'en': 'identification', 'ko': '신원 확인, 동일시'},
    {'en': 'personally', 'ko': '개인적으로, 직접'},
    {'en': 'interpret', 'ko': '해석하다, 통역하다'},
    {'en': 'attack', 'ko': '공격, 공격하다'},
    {'en': 'associate', 'ko': '연관시키다, 교제하다'},
    {'en': 'situation', 'ko': '상황'},
    {'en': 'generate', 'ko': '발생시키다, 만들어내다'},
    {'en': 'positive', 'ko': '긍정적인'},
    {'en': 'northern', 'ko': '북부의'},
    {'en': 'sorrow', 'ko': '슬픔, 비애'},
    {'en': 'probably', 'ko': '아마도'},
    {'en': 'flip', 'ko': '뒤집다, 휙 넘기다'},
    {'en': 'affect', 'ko': '영향을 미치다'},
    {'en': 'equate', 'ko': '동일시하다'},
    {'en': 'tragedy', 'ko': '비극'},
    {'en': 'experience', 'ko': '경험, 경험하다'},
    {'en': 'compassion', 'ko': '연민, 동정'},
    {'en': 'hurt', 'ko': '상처, 다치게 하다'},
    {'en': 'involve', 'ko': '연루시키다, 포함하다'},

    # Passage 4
    {'en': 'embrace', 'ko': '포용하다, 받아들이다'},
    {'en': 'failure', 'ko': '실패'},
    {'en': 'related', 'ko': '관련된'},
    {'en': 'notion', 'ko': '개념, 관념'},
    {'en': 'particularly', 'ko': '특히'},
    {'en': 'complex', 'ko': '복잡한'},
    {'en': 'improve', 'ko': '개선하다, 향상시키다'},
    {'en': 'examine', 'ko': '조사하다, 검토하다'},
    {'en': 'limit', 'ko': '한계, 제한하다'},
    {'en': 'force', 'ko': '강제하다, 힘'},
    {'en': 'software', 'ko': '소프트웨어'},
    {'en': 'quality', 'ko': '품질, 질'},
    {'en': 'employ', 'ko': '고용하다, 이용하다'},
    {'en': 'engineer', 'ko': '엔지니어, 기사'},
    {'en': 'systematically', 'ko': '체계적으로'},
    {'en': 'similarly', 'ko': '마찬가지로'},
    {'en': 'troubleshoot', 'ko': '문제를 해결하다'},
    {'en': 'complicated', 'ko': '복잡한'},
    {'en': 'device', 'ko': '장치, 기기'},
    {'en': 'deliberately', 'ko': '의도적으로'},
    {'en': 'temporary', 'ko': '일시적인, 임시의'},
    {'en': 'multiple', 'ko': '다수의, 다양한'},
    {'en': 'function', 'ko': '기능, 역할을 하다'},
    {'en': 'locate', 'ko': '위치를 찾아내다'},
    {'en': 'actual', 'ko': '실제의'},
    {'en': 'dysfunction', 'ko': '기능 장애'},
    {'en': 'respect', 'ko': '존중, 존경'},
    {'en': 'surprise', 'ko': '놀라게 하다'},
    {'en': 'patience', 'ko': '인내심'},
    {'en': 'puzzle', 'ko': '당황하게 하다, 퍼즐'},
    {'en': 'outsider', 'ko': '외부인, 국외자'},
    {'en': 'habit', 'ko': '습관'},
    {'en': 'essential', 'ko': '필수적인, 본질적인'},
    {'en': 'trick', 'ko': '비결, 속임수'},
    {'en': 'success', 'ko': '성공'},

    # Passage 5
    {'en': 'event', 'ko': '사건, 행사'},
    {'en': 'state', 'ko': '상태, 국가'},
    {'en': 'vivid', 'ko': '생생한, 선명한'},
    {'en': 'memory', 'ko': '기억, 기억력'},
    {'en': 'pattern', 'ko': '무늬, 패턴'},
    {'en': 'heighten', 'ko': '고조시키다, 높이다'},
    {'en': 'cause', 'ko': '유발하다, 원인'},
    {'en': 'itself', 'ko': '그 자체'},
    {'en': 'brain', 'ko': '뇌'},
    {'en': 'chemical', 'ko': '화학적인, 화학물질'},
    {'en': 'shocking', 'ko': '충격적인'},
    {'en': 'extremely', 'ko': '극도로, 대단히'},
    {'en': 'release', 'ko': '방출하다, 풀어주다'},
    {'en': 'special', 'ko': '특별한'},
    {'en': 'hormone', 'ko': '호르몬'},
    {'en': 'nerve', 'ko': '신경'},
    {'en': 'exceptionally', 'ko': '유난히, 예외적으로'},
    {'en': 'receptive', 'ko': '수용적인, 잘 받아들이는'},
    {'en': 'enable', 'ko': '가능하게 하다'},
    {'en': 'insignificant', 'ko': '사소한, 중요하지 않은'},
    {'en': 'detail', 'ko': '세부 사항'},
    {'en': 'record', 'ko': '기록하다, 기록'},
    {'en': 'unusual', 'ko': '이례적인, 특이한'},
    {'en': 'amount', 'ko': '양, 총액'},
    {'en': 'include', 'ko': '포함하다'},
    {'en': 'intense', 'ko': '강렬한, 극심한'},
    {'en': 'account for', 'ko': '설명하다, 차지하다'},
    {'en': 'recall', 'ko': '회상하다, 기억해내다'},

    # Passage 6
    {'en': 'traditionally', 'ko': '전통적으로'},
    {'en': 'forget', 'ko': '잊다, 망각하다'},
    {'en': 'regard', 'ko': '여기다, 간주하다'},
    {'en': 'passive', 'ko': '수동적인, 소극적인'},
    {'en': 'decay', 'ko': '부패하다, 쇠퇴하다'},
    {'en': 'information', 'ko': '정보'},
    {'en': 'store', 'ko': '저장하다, 가게'},
    {'en': 'fade', 'ko': '서서히 사라지다, 바래다'},
    {'en': 'sunlight', 'ko': '햇빛'},
    {'en': 'recent', 'ko': '최근의'},
    {'en': 'research', 'ko': '연구, 조사하다'},
    {'en': 'suggest', 'ko': '시사하다, 제안하다'},
    {'en': 'intentional', 'ko': '의도적인'},
    {'en': 'erasure', 'ko': '삭제, 지우기'},
    {'en': 'arrange', 'ko': '준비하다, 배열하다'},
    {'en': 'elaborate', 'ko': '정교한, 공들인'},
    {'en': 'cellular', 'ko': '세포의, 휴대전화의'},
    {'en': 'molecular', 'ko': '분자의'},
    {'en': 'forgetfulness', 'ko': '건망증'},
    {'en': 'necessarily', 'ko': '반드시 ~인 것은 아닌'},
    {'en': 'sign', 'ko': '징후, 신호'},
    {'en': 'faulty', 'ko': '결함이 있는, 잘못된'},
    {'en': 'computational', 'ko': '계산의'},
    {'en': 'model', 'ko': '모델, 모형'},
    {'en': 'animal', 'ko': '동물'},
    {'en': 'intelligent', 'ko': '지능적인, 똑똑한'},
    {'en': 'preserve', 'ko': '보존하다, 지키다'},
    {'en': 'sound', 'ko': '타당한, 소리'},
    {'en': 'decision', 'ko': '결정, 결단력'},

    # Passage 7
    {'en': 'separate', 'ko': '분리된, 독립된'},
    {'en': 'connect', 'ko': '연결하다'},
    {'en': 'understand', 'ko': '이해하다'},
    {'en': 'consumer', 'ko': '소비자'},
    {'en': 'choice', 'ko': '선택'},
    {'en': 'western', 'ko': '서구의, 서쪽의'},
    {'en': 'culture', 'ko': '문화'},
    {'en': 'view', 'ko': '견해, 간주하다'},
    {'en': 'act', 'ko': '행동, 행동하다'},
    {'en': 'expression', 'ko': '표현'},
    {'en': 'desirable', 'ko': '바람직한'},
    {'en': 'consumption', 'ko': '소비'},
    {'en': 'represent', 'ko': '대표하다, 나타내다'},
    {'en': 'vary', 'ko': '다르게 하다, 변화를 주다'},
    {'en': 'purchase', 'ko': '구매하다, 구매'},
    {'en': 'attempt', 'ko': '시도, 시도하다'},
    {'en': 'bias', 'ko': '편향, 편견'},
    {'en': 'behavioral', 'ko': '행동의'},
    {'en': 'economics', 'ko': '경제학'},
    {'en': 'psychological', 'ko': '심리적인'},
    {'en': 'impact', 'ko': '영향, 충격'},
    {'en': 'strategy', 'ko': '전략'},
    {'en': 'variety', 'ko': '다양성, 여러 가지'},
    {'en': 'emphasize', 'ko': '강조하다'},
    {'en': 'interpersonal', 'ko': '대인 관계의'},
    {'en': 'task', 'ko': '과업, 일'},
    {'en': 'portray', 'ko': '묘사하다, 보여주다'},
    {'en': 'favorable', 'ko': '호의적인, 유리한'},
    {'en': 'concern', 'ko': '관심사, 우려'},
    {'en': 'subsequently', 'ko': '그 후에, 결과적으로'},
    {'en': 'context', 'ko': '맥락, 환경'},

    # Passage 8
    {'en': 'philosopher', 'ko': '철학자'},
    {'en': 'century', 'ko': '세기, 100년'},
    {'en': 'debate', 'ko': '논쟁하다, 토론'},
    {'en': 'nature', 'ko': '본질, 자연'},
    {'en': 'reality', 'ko': '실재, 현실'},
    {'en': 'illusion', 'ko': '환상, 착각'},
    {'en': 'modern', 'ko': '현대의, 근대의'},
    {'en': 'neuroscience', 'ko': '신경 과학'},
    {'en': 'teach', 'ko': '가르치다'},
    {'en': 'perception', 'ko': '지각, 인식'},
    {'en': 'indirectly', 'ko': '간접적으로'},
    {'en': 'process', 'ko': '과정, 처리하다'},
    {'en': 'raw', 'ko': '가공되지 않은, 날것의'},
    {'en': 'data', 'ko': '데이터, 자료'},
    {'en': 'sense', 'ko': '감각, 느끼다'},
    {'en': 'unconscious', 'ko': '무의식적인'},
    {'en': 'create', 'ko': '창조하다, 만들다'},
    {'en': 'dimensional', 'ko': '차원의'},
    {'en': 'direct', 'ko': '직접적인, 향하다'},
    {'en': 'flat', 'ko': '평평한'},
    {'en': 'array', 'ko': '배열, 집합'},
    {'en': 'retina', 'ko': '망막'},
    {'en': 'sensation', 'ko': '감각, 느낌'},
    {'en': 'mind', 'ko': '마음, 정신'},
    {'en': 'image', 'ko': '이미지, 형상'},
    {'en': 'vision', 'ko': '시력, 시야'},
    {'en': 'upside down', 'ko': '거꾸로'},
    {'en': 'remove', 'ko': '제거하다, 없애다'},

    # Passage 9
    {'en': 'surface', 'ko': '표면'},
    {'en': 'volume', 'ko': '부피'},
    {'en': 'ratio', 'ko': '비율'},
    {'en': 'maintain', 'ko': '유지하다'},
    {'en': 'constant', 'ko': '일정한, 끊임없는'},
    {'en': 'temperature', 'ko': '온도, 기온'},
    {'en': 'main', 'ko': '주요한'},
    {'en': 'warm-blooded', 'ko': '온혈의'},
    {'en': 'metabolic', 'ko': '신진대사의'},
    {'en': 'decline', 'ko': '감소하다, 거절하다'},
    {'en': 'increase', 'ko': '증가하다, 증가'},
    {'en': 'size', 'ko': '크기'},
    {'en': 'mammal', 'ko': '포유동물'},
    {'en': 'evolve', 'ko': '진화하다'},
    {'en': 'relatively', 'ko': '상대적으로'},
    {'en': 'faster', 'ko': '더 빠른'},
    {'en': 'tend to', 'ko': '~하는 경향이 있다'},
    {'en': 'cold-blooded', 'ko': '냉혈의'},
    {'en': 'conversely', 'ko': '반대로, 역으로'},
    {'en': 'effort', 'ko': '노력'},
    {'en': 'allow', 'ko': '허락하다, 가능하게 하다'},
    {'en': 'heart failure', 'ko': '심장 마비'}
]

out = 'const english_3221m_vocab = ' + json.dumps(vocab, ensure_ascii=False, indent=4) + ';\n'
with codecs.open('C:/Users/User/Downloads/ISHS_Lab/data/english/english_3221m_vocab_part1.js', 'w', 'utf8') as f:
    f.write(out)

